CREATE TABLE IF NOT EXISTS schema_migrations (
  filename TEXT PRIMARY KEY,
  applied_at TEXT NOT NULL
);

CREATE TABLE carriers (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE UNIQUE INDEX carriers_name_unique ON carriers (lower(name));

CREATE TABLE lines_of_business (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE UNIQUE INDEX lines_of_business_name_unique ON lines_of_business (lower(name));

CREATE TABLE account_managers (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE UNIQUE INDEX account_managers_name_unique ON account_managers (lower(name));

CREATE TABLE agents (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  default_compensation_bps INTEGER,
  notes TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  CHECK (
    default_compensation_bps IS NULL
    OR (default_compensation_bps >= 0 AND default_compensation_bps <= 10000)
  )
);

CREATE TABLE groups (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  group_number TEXT,
  notes TEXT,
  account_manager_id INTEGER REFERENCES account_managers (id),
  primary_agent_id INTEGER REFERENCES agents (id),
  default_compensation_bps INTEGER,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE INDEX groups_account_manager_idx ON groups (account_manager_id);
CREATE INDEX groups_primary_agent_idx ON groups (primary_agent_id);

CREATE TABLE import_statements (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  original_filename TEXT NOT NULL,
  display_name TEXT NOT NULL,
  paid_month TEXT NOT NULL,
  uploaded_at TEXT NOT NULL,
  source_type TEXT NOT NULL,
  status TEXT NOT NULL,
  fingerprint TEXT NOT NULL,
  row_count INTEGER NOT NULL DEFAULT 0,
  new_group_count INTEGER NOT NULL DEFAULT 0,
  preview_json TEXT,
  stored_path TEXT,
  column_mapping_json TEXT,
  posted_row_count INTEGER NOT NULL DEFAULT 0,
  carrier_id INTEGER REFERENCES carriers (id),
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  CHECK (paid_month ~ '^[0-9]{4}-[0-9]{2}$')
);

CREATE UNIQUE INDEX import_statements_fingerprint_unique ON import_statements (fingerprint);
CREATE INDEX import_statements_paid_month_idx ON import_statements (paid_month);
CREATE INDEX import_statements_carrier_idx ON import_statements (carrier_id);

CREATE TABLE group_compensation_agreements (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id INTEGER NOT NULL REFERENCES groups (id),
  agent_id INTEGER NOT NULL REFERENCES agents (id),
  line_of_business_id INTEGER NOT NULL REFERENCES lines_of_business (id),
  compensation_bps INTEGER NOT NULL,
  effective_start TEXT NOT NULL,
  effective_end TEXT,
  status TEXT NOT NULL DEFAULT 'active',
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  CHECK (compensation_bps > 0 AND compensation_bps <= 10000),
  CHECK (effective_start ~ '^[0-9]{4}-[0-9]{2}$'),
  CHECK (effective_end IS NULL OR effective_end ~ '^[0-9]{4}-[0-9]{2}$'),
  CHECK (effective_end IS NULL OR effective_end >= effective_start),
  CHECK (status IN ('active', 'inactive'))
);

CREATE INDEX group_comp_agreements_lookup_idx
  ON group_compensation_agreements (group_id, agent_id, line_of_business_id, effective_start);
CREATE INDEX group_comp_agreements_group_idx ON group_compensation_agreements (group_id);
CREATE INDEX group_comp_agreements_agent_idx ON group_compensation_agreements (agent_id);

CREATE TABLE commission_records (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  statement_month TEXT NOT NULL,
  group_id INTEGER NOT NULL REFERENCES groups (id),
  carrier_id INTEGER NOT NULL REFERENCES carriers (id),
  line_of_business_id INTEGER NOT NULL REFERENCES lines_of_business (id),
  agent_id INTEGER REFERENCES agents (id),
  premium_cents INTEGER,
  gross_commission_cents INTEGER NOT NULL,
  compensation_bps INTEGER,
  agent_compensation_cents INTEGER NOT NULL,
  agency_net_cents INTEGER NOT NULL,
  source_reference TEXT,
  notes TEXT,
  premium_month TEXT,
  import_statement_id INTEGER REFERENCES import_statements (id),
  source_row_key TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  CHECK (statement_month ~ '^[0-9]{4}-[0-9]{2}$'),
  CHECK (
    compensation_bps IS NULL
    OR (compensation_bps >= 0 AND compensation_bps <= 10000)
  ),
  CHECK (agency_net_cents = gross_commission_cents - agent_compensation_cents)
);

CREATE INDEX commission_records_month_idx ON commission_records (statement_month);
CREATE INDEX commission_records_group_idx ON commission_records (group_id);
CREATE INDEX commission_records_carrier_idx ON commission_records (carrier_id);
CREATE INDEX commission_records_agent_idx ON commission_records (agent_id);
CREATE UNIQUE INDEX commission_records_import_row_unique
  ON commission_records (import_statement_id, source_row_key)
  WHERE import_statement_id IS NOT NULL AND source_row_key IS NOT NULL;

CREATE OR REPLACE FUNCTION prevent_overlapping_compensation_agreements()
RETURNS trigger AS $$
BEGIN
  IF NEW.compensation_bps <= 0 OR NEW.compensation_bps > 10000 THEN
    RAISE EXCEPTION 'compensation agreement split must be greater than 0 and no more than 100 percent';
  END IF;

  IF NEW.status = 'active' AND EXISTS (
    SELECT 1
    FROM group_compensation_agreements AS existing
    WHERE existing.status = 'active'
      AND existing.id IS DISTINCT FROM NEW.id
      AND existing.group_id = NEW.group_id
      AND existing.line_of_business_id = NEW.line_of_business_id
      AND NEW.effective_start <= COALESCE(existing.effective_end, '9999-12')
      AND existing.effective_start <= COALESCE(NEW.effective_end, '9999-12')
  ) THEN
    RAISE EXCEPTION 'overlapping active compensation agreement for group and line of business';
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER group_comp_agreements_validate_insert
BEFORE INSERT ON group_compensation_agreements
FOR EACH ROW
EXECUTE FUNCTION prevent_overlapping_compensation_agreements();

CREATE TRIGGER group_comp_agreements_validate_update
BEFORE UPDATE ON group_compensation_agreements
FOR EACH ROW
EXECUTE FUNCTION prevent_overlapping_compensation_agreements();
