CREATE TABLE IF NOT EXISTS carrier_statement_layouts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  carrier_id INTEGER NOT NULL REFERENCES carriers(id),
  name TEXT NOT NULL,
  version INTEGER NOT NULL,
  status TEXT NOT NULL,
  detection_signature_json TEXT NOT NULL,
  mapping_json TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS carrier_statement_layouts_carrier_name_version
  ON carrier_statement_layouts (carrier_id, name, version);

ALTER TABLE import_statements
  ADD COLUMN IF NOT EXISTS layout_id INTEGER REFERENCES carrier_statement_layouts(id);

ALTER TABLE import_statements
  ADD COLUMN IF NOT EXISTS layout_version INTEGER;

ALTER TABLE import_statements
  ADD COLUMN IF NOT EXISTS extraction_path TEXT;

ALTER TABLE carrier_statement_layouts ENABLE ROW LEVEL SECURITY;
