CREATE TABLE IF NOT EXISTS teams (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'active',
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  CHECK (status IN ('active', 'inactive'))
);

CREATE UNIQUE INDEX IF NOT EXISTS teams_name_unique ON teams (lower(name));

CREATE TABLE IF NOT EXISTS team_memberships (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_id INTEGER NOT NULL REFERENCES teams (id),
  person_kind TEXT NOT NULL,
  person_id INTEGER NOT NULL,
  share_bps INTEGER NOT NULL,
  effective_start TEXT NOT NULL,
  effective_end TEXT,
  status TEXT NOT NULL DEFAULT 'active',
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  CHECK (person_kind IN ('agent', 'account_manager')),
  CHECK (share_bps > 0 AND share_bps <= 10000),
  CHECK (effective_start ~ '^[0-9]{4}-(0[1-9]|1[0-2])$'),
  CHECK (effective_end IS NULL OR effective_end ~ '^[0-9]{4}-(0[1-9]|1[0-2])$'),
  CHECK (effective_end IS NULL OR effective_end >= effective_start),
  CHECK (status IN ('active', 'inactive'))
);

CREATE INDEX IF NOT EXISTS team_memberships_team_idx ON team_memberships (team_id);
CREATE INDEX IF NOT EXISTS team_memberships_person_idx ON team_memberships (person_kind, person_id);

CREATE TABLE IF NOT EXISTS compensation_allocations (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id INTEGER NOT NULL REFERENCES groups (id),
  line_of_business_id INTEGER NOT NULL REFERENCES lines_of_business (id),
  effective_start TEXT NOT NULL,
  effective_end TEXT,
  status TEXT NOT NULL DEFAULT 'active',
  source_agreement_id INTEGER REFERENCES group_compensation_agreements (id),
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  CHECK (effective_start ~ '^[0-9]{4}-(0[1-9]|1[0-2])$'),
  CHECK (effective_end IS NULL OR effective_end ~ '^[0-9]{4}-(0[1-9]|1[0-2])$'),
  CHECK (effective_end IS NULL OR effective_end >= effective_start),
  CHECK (status IN ('active', 'inactive'))
);

CREATE UNIQUE INDEX IF NOT EXISTS compensation_allocations_source_agreement_unique
  ON compensation_allocations (source_agreement_id)
  WHERE source_agreement_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS compensation_allocations_lookup_idx
  ON compensation_allocations (group_id, line_of_business_id, effective_start);

CREATE TABLE IF NOT EXISTS compensation_allocation_entries (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  allocation_id INTEGER NOT NULL REFERENCES compensation_allocations (id) ON DELETE CASCADE,
  recipient_type TEXT NOT NULL,
  person_kind TEXT,
  person_id INTEGER,
  team_id INTEGER REFERENCES teams (id),
  compensation_bps INTEGER NOT NULL,
  sort_order INTEGER NOT NULL DEFAULT 0,
  CHECK (recipient_type IN ('agency', 'person', 'team')),
  CHECK (compensation_bps > 0 AND compensation_bps <= 10000),
  CHECK (
    (recipient_type = 'agency' AND person_id IS NULL AND team_id IS NULL)
    OR (recipient_type = 'person' AND person_kind IN ('agent', 'account_manager') AND person_id IS NOT NULL AND team_id IS NULL)
    OR (recipient_type = 'team' AND team_id IS NOT NULL AND person_id IS NULL)
  )
);

CREATE INDEX IF NOT EXISTS compensation_allocation_entries_allocation_idx
  ON compensation_allocation_entries (allocation_id);

CREATE UNIQUE INDEX IF NOT EXISTS compensation_allocation_entries_agency_unique
  ON compensation_allocation_entries (allocation_id)
  WHERE recipient_type = 'agency';

CREATE UNIQUE INDEX IF NOT EXISTS compensation_allocation_entries_person_unique
  ON compensation_allocation_entries (allocation_id, person_kind, person_id)
  WHERE recipient_type = 'person';

CREATE UNIQUE INDEX IF NOT EXISTS compensation_allocation_entries_team_unique
  ON compensation_allocation_entries (allocation_id, team_id)
  WHERE recipient_type = 'team';

CREATE TABLE IF NOT EXISTS commission_payouts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  commission_id INTEGER NOT NULL REFERENCES commission_records (id) ON DELETE CASCADE,
  allocation_id INTEGER REFERENCES compensation_allocations (id),
  recipient_type TEXT NOT NULL,
  person_kind TEXT,
  person_id INTEGER,
  person_name TEXT,
  team_id INTEGER,
  team_name TEXT,
  parent_payout_id INTEGER REFERENCES commission_payouts (id),
  allocation_bps INTEGER NOT NULL,
  team_internal_bps INTEGER,
  compensation_cents INTEGER NOT NULL,
  created_at TEXT NOT NULL,
  CHECK (recipient_type IN ('agency', 'person', 'team', 'team_member')),
  CHECK (allocation_bps >= 0 AND allocation_bps <= 10000)
);

CREATE INDEX IF NOT EXISTS commission_payouts_commission_idx ON commission_payouts (commission_id);
CREATE INDEX IF NOT EXISTS commission_payouts_allocation_idx ON commission_payouts (allocation_id);
CREATE INDEX IF NOT EXISTS commission_payouts_person_idx ON commission_payouts (person_kind, person_id);
CREATE INDEX IF NOT EXISTS commission_payouts_team_idx ON commission_payouts (team_id);

CREATE OR REPLACE FUNCTION prevent_overlapping_compensation_allocations()
RETURNS trigger AS $$
BEGIN
  IF NEW.status = 'active' AND EXISTS (
    SELECT 1
    FROM compensation_allocations AS existing
    WHERE existing.status = 'active'
      AND existing.id IS DISTINCT FROM NEW.id
      AND existing.group_id = NEW.group_id
      AND existing.line_of_business_id = NEW.line_of_business_id
      AND NEW.effective_start <= COALESCE(existing.effective_end, '9999-12')
      AND existing.effective_start <= COALESCE(NEW.effective_end, '9999-12')
  ) THEN
    RAISE EXCEPTION 'overlapping active compensation allocation for group and line of business';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS compensation_allocations_validate_insert ON compensation_allocations;
CREATE TRIGGER compensation_allocations_validate_insert
BEFORE INSERT ON compensation_allocations
FOR EACH ROW
EXECUTE FUNCTION prevent_overlapping_compensation_allocations();

DROP TRIGGER IF EXISTS compensation_allocations_validate_update ON compensation_allocations;
CREATE TRIGGER compensation_allocations_validate_update
BEFORE UPDATE ON compensation_allocations
FOR EACH ROW
EXECUTE FUNCTION prevent_overlapping_compensation_allocations();

INSERT INTO compensation_allocations (
  group_id,
  line_of_business_id,
  effective_start,
  effective_end,
  status,
  source_agreement_id,
  created_at,
  updated_at
)
SELECT
  group_id,
  line_of_business_id,
  effective_start,
  effective_end,
  'inactive',
  id,
  created_at,
  updated_at
FROM group_compensation_agreements
WHERE NOT EXISTS (
  SELECT 1
  FROM compensation_allocations AS existing
  WHERE existing.source_agreement_id = group_compensation_agreements.id
);

INSERT INTO compensation_allocation_entries (
  allocation_id,
  recipient_type,
  person_kind,
  person_id,
  team_id,
  compensation_bps,
  sort_order
)
SELECT
  allocation.id,
  'person',
  'agent',
  agreement.agent_id,
  NULL,
  agreement.compensation_bps,
  0
FROM compensation_allocations AS allocation
INNER JOIN group_compensation_agreements AS agreement
  ON agreement.id = allocation.source_agreement_id
WHERE NOT EXISTS (
  SELECT 1
  FROM compensation_allocation_entries AS entry
  WHERE entry.allocation_id = allocation.id
);

CREATE OR REPLACE FUNCTION validate_compensation_allocation_activation()
RETURNS trigger AS $$
DECLARE
  total_bps INTEGER;
  direct_people INTEGER;
BEGIN
  IF NEW.status <> 'active' THEN
    RETURN NEW;
  END IF;
  IF TG_OP = 'INSERT' THEN
    RAISE EXCEPTION 'compensation allocations must be created inactive and activated after entries are complete';
  END IF;
  SELECT COALESCE(SUM(compensation_bps), 0),
         COUNT(*) FILTER (WHERE recipient_type = 'person')
    INTO total_bps, direct_people
    FROM compensation_allocation_entries
   WHERE allocation_id = NEW.id;
  IF total_bps <> 10000 THEN
    RAISE EXCEPTION 'active compensation allocation must total exactly 10000 basis points';
  END IF;
  IF direct_people > 3 THEN
    RAISE EXCEPTION 'active compensation allocation may include at most 3 direct people';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION prevent_active_allocation_entry_changes()
RETURNS trigger AS $$
DECLARE
  target_allocation_id INTEGER;
  target_status TEXT;
BEGIN
  target_allocation_id := CASE WHEN TG_OP = 'DELETE' THEN OLD.allocation_id ELSE NEW.allocation_id END;
  SELECT status INTO target_status FROM compensation_allocations WHERE id = target_allocation_id;
  IF target_status = 'active' OR EXISTS (
    SELECT 1 FROM commission_payouts WHERE allocation_id = target_allocation_id
  ) THEN
    RAISE EXCEPTION 'active or used compensation allocation entries are immutable; create a new allocation version';
  END IF;
  RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION prevent_active_allocation_identity_changes()
RETURNS trigger AS $$
BEGIN
  IF (
    OLD.status = 'active'
    OR EXISTS (SELECT 1 FROM commission_payouts WHERE allocation_id = OLD.id)
  ) AND (
    NEW.group_id IS DISTINCT FROM OLD.group_id
    OR NEW.line_of_business_id IS DISTINCT FROM OLD.line_of_business_id
    OR NEW.effective_start IS DISTINCT FROM OLD.effective_start
    OR NEW.source_agreement_id IS DISTINCT FROM OLD.source_agreement_id
  ) THEN
    RAISE EXCEPTION 'active or used compensation allocation identity is immutable; create a new allocation version';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS compensation_allocations_validate_activation ON compensation_allocations;
CREATE TRIGGER compensation_allocations_validate_activation
BEFORE INSERT OR UPDATE ON compensation_allocations
FOR EACH ROW
EXECUTE FUNCTION validate_compensation_allocation_activation();

DROP TRIGGER IF EXISTS compensation_allocation_entries_immutable ON compensation_allocation_entries;
CREATE TRIGGER compensation_allocation_entries_immutable
BEFORE INSERT OR UPDATE OR DELETE ON compensation_allocation_entries
FOR EACH ROW
EXECUTE FUNCTION prevent_active_allocation_entry_changes();

DROP TRIGGER IF EXISTS compensation_allocations_identity_immutable ON compensation_allocations;
CREATE TRIGGER compensation_allocations_identity_immutable
BEFORE UPDATE ON compensation_allocations
FOR EACH ROW
EXECUTE FUNCTION prevent_active_allocation_identity_changes();

UPDATE compensation_allocations AS allocation
SET status = 'active'
FROM group_compensation_agreements AS agreement
WHERE allocation.source_agreement_id = agreement.id
  AND agreement.compensation_bps = 10000
  AND agreement.status = 'active';

ALTER TABLE teams ENABLE ROW LEVEL SECURITY;
ALTER TABLE team_memberships ENABLE ROW LEVEL SECURITY;
ALTER TABLE compensation_allocations ENABLE ROW LEVEL SECURITY;
ALTER TABLE compensation_allocation_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE commission_payouts ENABLE ROW LEVEL SECURITY;
