CREATE TABLE IF NOT EXISTS carrier_coverage_aliases (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  carrier_id INTEGER NOT NULL REFERENCES carriers (id),
  source_value TEXT NOT NULL,
  line_of_business_id INTEGER NOT NULL REFERENCES lines_of_business (id),
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  CHECK (source_value = lower(btrim(source_value)))
);

CREATE UNIQUE INDEX IF NOT EXISTS carrier_coverage_aliases_carrier_source_unique
  ON carrier_coverage_aliases (carrier_id, source_value);

CREATE INDEX IF NOT EXISTS carrier_coverage_aliases_carrier_idx
  ON carrier_coverage_aliases (carrier_id);

ALTER TABLE carrier_coverage_aliases ENABLE ROW LEVEL SECURITY;
