CREATE TABLE IF NOT EXISTS carrier_group_identities (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  carrier_id INTEGER NOT NULL REFERENCES carriers (id),
  external_group_number TEXT NOT NULL,
  group_id INTEGER NOT NULL REFERENCES groups (id),
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  CHECK (external_group_number = lower(regexp_replace(btrim(external_group_number), '\s+', ' ', 'g')))
);

CREATE UNIQUE INDEX IF NOT EXISTS carrier_group_identities_carrier_number_unique
  ON carrier_group_identities (carrier_id, external_group_number);

CREATE INDEX IF NOT EXISTS carrier_group_identities_carrier_idx
  ON carrier_group_identities (carrier_id);

CREATE INDEX IF NOT EXISTS carrier_group_identities_group_idx
  ON carrier_group_identities (group_id);

ALTER TABLE carrier_group_identities ENABLE ROW LEVEL SECURITY;
