CREATE TABLE IF NOT EXISTS compensation_correction_batches (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  confirmation_key TEXT NOT NULL,
  preview_token TEXT NOT NULL,
  request_fingerprint TEXT NOT NULL,
  reason TEXT NOT NULL,
  initiator_id TEXT,
  initiator_email TEXT,
  initiator_name TEXT,
  created_at TEXT NOT NULL,
  CHECK (btrim(confirmation_key) <> ''),
  CHECK (btrim(preview_token) <> ''),
  CHECK (btrim(request_fingerprint) <> ''),
  CHECK (btrim(reason) <> '')
);

CREATE UNIQUE INDEX IF NOT EXISTS compensation_correction_batches_confirmation_key_unique
  ON compensation_correction_batches (confirmation_key);

CREATE TABLE IF NOT EXISTS compensation_correction_items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  batch_id INTEGER NOT NULL REFERENCES compensation_correction_batches (id),
  commission_id INTEGER NOT NULL REFERENCES commission_records (id),
  paid_month TEXT NOT NULL,
  allocation_id INTEGER NOT NULL REFERENCES compensation_allocations (id),
  original_payouts_json TEXT NOT NULL,
  original_agent_compensation_cents INTEGER NOT NULL,
  original_agency_net_cents INTEGER NOT NULL,
  original_gross_commission_cents INTEGER NOT NULL,
  corrected_payouts_json TEXT NOT NULL,
  corrected_agent_compensation_cents INTEGER NOT NULL,
  corrected_agency_net_cents INTEGER NOT NULL,
  created_at TEXT NOT NULL,
  CHECK (paid_month ~ '^[0-9]{4}-(0[1-9]|1[0-2])$'),
  CHECK (original_gross_commission_cents = original_agency_net_cents + original_agent_compensation_cents),
  CHECK (original_gross_commission_cents = corrected_agency_net_cents + corrected_agent_compensation_cents)
);

CREATE UNIQUE INDEX IF NOT EXISTS compensation_correction_items_commission_unique
  ON compensation_correction_items (commission_id);

CREATE INDEX IF NOT EXISTS compensation_correction_items_batch_idx
  ON compensation_correction_items (batch_id);

CREATE INDEX IF NOT EXISTS compensation_correction_items_paid_month_idx
  ON compensation_correction_items (paid_month);

ALTER TABLE compensation_correction_batches ENABLE ROW LEVEL SECURITY;
ALTER TABLE compensation_correction_items ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION prevent_compensation_correction_mutation()
RETURNS trigger AS $$
BEGIN
  RAISE EXCEPTION 'compensation correction audit records are immutable';
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS compensation_correction_batches_immutable ON compensation_correction_batches;
CREATE TRIGGER compensation_correction_batches_immutable
BEFORE UPDATE OR DELETE ON compensation_correction_batches
FOR EACH ROW
EXECUTE FUNCTION prevent_compensation_correction_mutation();

DROP TRIGGER IF EXISTS compensation_correction_items_immutable ON compensation_correction_items;
CREATE TRIGGER compensation_correction_items_immutable
BEFORE UPDATE OR DELETE ON compensation_correction_items
FOR EACH ROW
EXECUTE FUNCTION prevent_compensation_correction_mutation();
