CREATE TABLE IF NOT EXISTS agency_compensation_owners (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agent_id INTEGER REFERENCES agents (id),
  account_manager_id INTEGER REFERENCES account_managers (id),
  effective_start_month TEXT NOT NULL,
  effective_end_month TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  CHECK (
    (agent_id IS NOT NULL AND account_manager_id IS NULL)
    OR (agent_id IS NULL AND account_manager_id IS NOT NULL)
  ),
  CHECK (effective_start_month ~ '^[0-9]{4}-(0[1-9]|1[0-2])$'),
  CHECK (effective_end_month IS NULL OR effective_end_month ~ '^[0-9]{4}-(0[1-9]|1[0-2])$'),
  CHECK (effective_end_month IS NULL OR effective_end_month >= effective_start_month)
);

CREATE OR REPLACE FUNCTION prevent_overlapping_agency_compensation_owners()
RETURNS trigger AS $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM agency_compensation_owners AS existing
    WHERE existing.id IS DISTINCT FROM NEW.id
      AND NEW.effective_start_month <= COALESCE(existing.effective_end_month, '9999-12')
      AND existing.effective_start_month <= COALESCE(NEW.effective_end_month, '9999-12')
  ) THEN
    RAISE EXCEPTION 'overlapping agency compensation owner period';
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS agency_compensation_owners_validate_insert ON agency_compensation_owners;
CREATE TRIGGER agency_compensation_owners_validate_insert
BEFORE INSERT ON agency_compensation_owners
FOR EACH ROW
EXECUTE FUNCTION prevent_overlapping_agency_compensation_owners();

DROP TRIGGER IF EXISTS agency_compensation_owners_validate_update ON agency_compensation_owners;
CREATE TRIGGER agency_compensation_owners_validate_update
BEFORE UPDATE ON agency_compensation_owners
FOR EACH ROW
EXECUTE FUNCTION prevent_overlapping_agency_compensation_owners();

ALTER TABLE agency_compensation_owners ENABLE ROW LEVEL SECURITY;

REVOKE EXECUTE ON FUNCTION prevent_overlapping_agency_compensation_owners() FROM PUBLIC;
