ALTER TABLE commission_records
  ADD COLUMN IF NOT EXISTS source_lob_label TEXT;

ALTER TABLE commission_records
  ADD COLUMN IF NOT EXISTS source_period_label TEXT;

CREATE TABLE IF NOT EXISTS statement_paid_month_changes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  statement_id INTEGER NOT NULL REFERENCES import_statements (id),
  confirmation_key TEXT NOT NULL,
  preview_token TEXT NOT NULL,
  request_fingerprint TEXT NOT NULL,
  old_paid_month TEXT NOT NULL,
  new_paid_month TEXT NOT NULL,
  commission_ids_json TEXT NOT NULL,
  commission_count INTEGER NOT NULL,
  gross_affected_cents INTEGER NOT NULL,
  impact_classification_json TEXT NOT NULL,
  payout_correction_required INTEGER NOT NULL,
  payout_correction_performed INTEGER NOT NULL,
  reason TEXT NOT NULL,
  initiator_id TEXT,
  initiator_email TEXT,
  initiator_name TEXT,
  created_at TEXT NOT NULL,
  CHECK (btrim(confirmation_key) <> ''),
  CHECK (btrim(preview_token) <> ''),
  CHECK (btrim(request_fingerprint) <> ''),
  CHECK (btrim(reason) <> ''),
  CHECK (old_paid_month ~ '^[0-9]{4}-(0[1-9]|1[0-2])$'),
  CHECK (new_paid_month ~ '^[0-9]{4}-(0[1-9]|1[0-2])$'),
  CHECK (old_paid_month <> new_paid_month),
  CHECK (commission_count >= 0),
  CHECK (payout_correction_required IN (0, 1)),
  CHECK (payout_correction_performed IN (0, 1))
);

CREATE UNIQUE INDEX IF NOT EXISTS statement_paid_month_changes_confirmation_key_unique
  ON statement_paid_month_changes (confirmation_key);

CREATE INDEX IF NOT EXISTS statement_paid_month_changes_statement_idx
  ON statement_paid_month_changes (statement_id);

CREATE INDEX IF NOT EXISTS statement_paid_month_changes_created_idx
  ON statement_paid_month_changes (created_at);

ALTER TABLE statement_paid_month_changes ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION prevent_statement_paid_month_change_mutation()
RETURNS trigger AS $$
BEGIN
  RAISE EXCEPTION 'statement paid-month change audit records are immutable';
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS statement_paid_month_changes_immutable ON statement_paid_month_changes;
CREATE TRIGGER statement_paid_month_changes_immutable
BEFORE UPDATE OR DELETE ON statement_paid_month_changes
FOR EACH ROW
EXECUTE FUNCTION prevent_statement_paid_month_change_mutation();
